### ISSUE TITLE
Build failure with Flutter 3.10.5

### ISSUE THREAD

**Issue by Matts** [harness/ff-flutter-client-sdk#28]
hi, I am receiving the following error when following the installation guide in the README.md:

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':ff_flutter_client_sdk' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

`flutter doctor`

```bash
[✓] Flutter (Channel stable, 3.10.5, on macOS 14.0 23A344 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2)
[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
[✓] Connected device (3 available)
[✓] Network resources
```

**Comment by erdirowlands** [comment]
Hi, @Matts  sorry for the delay in getting back to you. 

We believe this issue should be fixed in ^2.1.1 .  I'll close this issue, if you are still running into problems can you email support@harness.io 

Thanks
