### ISSUE TITLE
Destroy future doesn't complete on iOS

### ISSUE THREAD

**Issue by curt-weber** [harness/ff-flutter-client-sdk#32]
When shutting down the plugin using [CfClient.destroy](https://pub.dev/documentation/ff_flutter_client_sdk/latest/ff_flutter_client_sdk/CfClient/destroy.html) on iOS the future never returns. The future completes and returns properly on Android.

We have to use a timeout to work around this issue as our automation tests need to start and shutdown the harness client between runs.

**Comment by erdirowlands** [comment]
Hi @curt-weber , thanks for raising this. 

Could you please submit a support ticket to support@harness.io as well, if you haven't done so already, so the issue can be tracked.

**Comment by erdirowlands** [comment]
Fix is in PR, pending review and release: https://github.com/harness/ff-flutter-client-sdk/pull/35

**Comment by curt-weber** [comment]
Verified fixed - thanks @erdirowlands!
